from langchain_community.utilities import SQLDatabase
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_google_genai import ChatGoogleGenerativeAI
from sqlalchemy import create_engine
from langchain_core.output_parsers import StrOutputParser # To ensure final output is a clean string
from operator import itemgetter 
import pandas as pd
import os

# --- 1. CONFIGURATION ---
DB_NAME = 'uber_analytics_db'
DB_USER = 'uber_analytics_user'
DB_PASS = 'eiv2025'
DB_HOST = 'localhost'
DB_PORT = '5432'
TABLE_NAME = 'cleaned_uber_rides'

# Global SQLAlchemy engine for manual query execution
DATABASE_URL = f"postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
try:
    ENGINE = create_engine(DATABASE_URL)
except Exception as e:
    print(f"Warning: Database engine failed to create. Ensure PostgreSQL is running. Error: {e}")
    ENGINE = None

# --- Helper Functions (Only needed for fetching data and schema) ---

def run_sql_query(sql_query):
    """Executes the final SQL query generated by the agent and returns a DataFrame."""
    if ENGINE is None:
        return "Error: Database engine not initialized."
    try:
        # Conversion happens here!
        df = pd.read_sql(sql_query, ENGINE) 
        return df
    except Exception as e:
        return f"Error executing query: {e}"

def get_schema(db_instance: SQLDatabase):
    """Returns the cleaned_uber_rides table schema as DDL."""
    # This uses the LangChain utility to get the schema details
    return db_instance.get_table_info(table_names=[TABLE_NAME])

# --- 2. CORE AGENT LOGIC: SQL Generator Chain ---

def setup_sql_agent():
    """Sets up a pure SQL Generator Chain that translates a question into an SQL query."""
    
    # 2a. Check for API Key
    if not os.getenv("GEMINI_API_KEY"):
        raise ValueError("GEMINI_API_KEY environment variable not set. Please set it in your terminal.")

    # 2b. Database Connection (Required for schema fetching)
    try:
        db = SQLDatabase.from_uri(
            database_uri=DATABASE_URL,
            include_tables=[TABLE_NAME],
            sample_rows_in_table_info=5,
            schema="public",
            view_support=True
        )
    except Exception as e:
        print(f"Failed to connect to PostgreSQL: {e}")
        return None

    # 2c. Initialize the LLM
    llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0)

    # 2d. Define the Strict System Prompt
    # This prompt is modified to be STRICTLY for generation, forcing the output to be JUST the query.
    SYSTEM_TEMPLATE = f"""
    You are an expert PostgreSQL data analyst chatbot specialized in ride-sharing data.
    Your ONLY job is to accurately translate the user's question into a single, valid, executable PostgreSQL query.

    CRITICAL RULE:
    - You MUST ONLY query the view named "{TABLE_NAME}".
    - DO NOT include any explanatory text, markdown formatting (e.g., ```sql), or conversational responses.
    - Your final and ONLY output MUST be the raw SQL query.

    --- CONTEXT ---
    1. The database view and its schema are:
    {{schema}}
    2. All numeric zero values (0) are treated as NULL and automatically excluded from AVG/SUM operations.
    3. When counting rides, use COUNT(booking_id).
    """

    prompt = ChatPromptTemplate.from_messages(
        [("system", SYSTEM_TEMPLATE), ("human", "{question}")]
    )
    
    # 2e. Construct the Generator Chain using LCEL
    # This uses itemgetter to correctly pass 'question' and 'schema' to the prompt.
    # The chain is: (Input Dict) -> (Schema + Question) -> (Prompt) -> (LLM Call) -> (Clean String)
    sql_generator_chain = (
        # 1. Prepare input: {question} is passed through, and {schema} is fetched
        RunnablePassthrough.assign(
            schema=lambda x: get_schema(db) # Pass the database instance to the getter
        )
        # 2. Format the prompt
        | prompt
        # 3. Call the LLM
        | llm.bind(stop=["\nSQL_START:"]) # Use a stop sequence as an extra constraint
        # 4. Clean the output to ensure it's a bare string
        | StrOutputParser()
    )
    
    print("SQL Generator Chain setup complete.")
    # The returned object is the new chain for your app.py to call.
    return sql_generator_chain

# ------------------------------------------------
if __name__ == '__main__':
    # Test case is now commented out to prevent running the chain every time the app is imported
    pass